servername: "YourServer.com"

mysql:
  host: localhost
  username: username
  password: password
  database: database
  port: 3306

yubico:
  enabled: false
  clientId: ''
  secretKey: ''

messages:
  authenabled: "&c[&42FA&c]&7 Deine Session ist abgelaufen. Daher musst du deine 2FA Code erneut bestätigen. &9Schreibe dafür deinen 6 Stelligen Code aus der App einfach in den Chat.&7 Keiner außer du wird ihn sehen."
  help: "&c[&42FA&c]&7 Mit 2FA kannst du deinen Account absichern und so verhindern da andere als du mit deinem Account hier Spielen können. Du benötigst dafür ein Handy mit Authy oder Google Authenticator. Wir helfen dir gerne bei einrichten, melde dich dafür einfach bei uns im TeamSpeak Support oder schreib uns auf Discord."
  activated: "&c[&42FA&c]&7 2FA wurde bei dir Aktiviert! Nutze diesen Code: &9&l%secret% &r oder diesen Link: %link% und aktiviere 2FA indem du /2fa activate <6 Stelliger Code aus der App> ausführst."
  alreadyactive: "&c[&42FA&c]&7 2FA ist bei dir bereits Aktiviert. Kein Grund es nochmals zu aktivieren."
  removeauth: "&c[&42FA&c]&7 2FA wurde von deinem Account entfernt."
  notloggedin: "&c[&42FA&c]&7 2FA ist bei dir nicht Aktiviert. Du kannst daher diese Aktion nicht ausführen."
  logoutmessage: "&c[&42FA&c]&7 Du wurdest abgemeldet. Sobald du dich erneut anmeldest wirst du erneut nach dem Code gefragt."
  missingcode: "&c[&42FA&c]&7 Es fehlt dein 6 stelliger Code. Nutze /2fa activate <6 stelliger Code>"
  errorocurred: "&c[&42FA&c]&7 Es ist ein Fehler aufgetreten. Versuche es bitte erneut, sollte es dann immer noch nicht funktionieren melde dich bitte bei uns im TeamSpeak (greev.eu) oder im Discord (https://discord.greev.eu)"
  codeisinvalid: "&c[&42FA&c]&7 Der angegebene Code ist ungültig! Bitte überprüfe ihn erneut. Bei Fehlern melde dich bitte bei uns im TeamSpeak (greev.eu) oder im Discord (https://discord.greev.eu)"
  successfulcctivated: "&c[&42FA&c]&7 Du hast deinen Account erfolgreich bestätigt. 2FA ist bei dir nun aktiv."
  needtoactivate: "&c[&42FA&c]&7 Es scheint so als wenn du 2FA bereits aktviert, jedoch noch nicht bestätigt hast. &c&lSo schützt es deinen Account noch nicht! &7Bestätige 2FA indem du /2fa activate <6 Stelliger Code aus der App> ausführst."
  loginsuccessful: "&c[&42FA&c]&7 Bestätigung erfolgreich! Du kannst nun normal Spielen."
  waitingforauthcode: "&c[&42FA&c]&7 Bitte gebe zuerst deinen 6 Stelligen Code im Chat ein, bevor du diese Aktion ausführst."
  forceenable: '&c[&42FA&c]&c You need to enable 2FA before you can play. Use &e/2fa&c to enable 2FA.'
  disableforforced: '&c[&42FA&c]&c You cant disable 2FA for your account!'
  yubico:
    activated: '&c[&42FA&c]&a Dein Yubico OTP wurde eingerichtet!'
    invalidcode: '&c[&42FA&c]&c Der Yubico OTP ist ungültig!'
    enabletotp: '&c[&42FA&c]&c Du musst TOTP erst aktiviert haben, bevor du Yubico OTP aktivieren kannst!'
    missingotp: '&c[&42FA&c]&c Bitte gebe den Yubico OTP Code mit an!'
  hovertext: "&cLink öffnen"
