servername: "YourServer.com"

mysql:
  host: "localhost"
  username: "username"
  password: "password"
  database: "database"
  port: 3306

yubico:
  enabled: false
  clientId: ""
  secretKey: ""

authserver:
  enabled: false
  name: "auth"

messages:
  authenabled: "&c[&42FA&c]&7 Your session has expired. Therefore you have to reconfirm your 2FA code.\n&9To do this, simply write your 6-digit code from the app in the chat.\n&7No one but you will see it."
  help: "&c[&42FA&c]&7 With 2FA you can secure your account and prevent others than you from playing here with your account. You'll need a mobile phone with Authy or Google Authenticator. We are happy to help you with the setup, just contact us on Discord."
  activated: "&c[&42FA&c]&7 2FA has been activated! Use this code: &9&l%secret% &ror this link: %link% to activate 2FA. An last but not least, run /2fa activate <6 digit code from the app> to enable it."
  alreadyactive: "&c[&42FA&c]&7 2FA is already activated for you. No need to activate it again."
  removeauth: "&c[&42FA&c]&a 2FA has been removed from your account."
  notloggedin: "&c[&42FA&c]&7 2FA is not activated for you. Therefore, you cannot perform this action."
  logoutmessage: "&c[&42FA&c]&a You have been logged out."
  missingcode: "&c[&42FA&c]&7 Your 6 digit code is missing. Use /2fa activate <6 digit code>"
  errorocurred: "&c[&42FA&c]&7 An error has occurred. Please try again, if it still doesn't work please contact us in TeamSpeak (greev.eu) or in our Discord (www.grv.sh/discord)."
  codeisinvalid: "&c[&42FA&c]&7 The given code is invalid! Please check it again. If it's not working, please contact us in TeamSpeak (greev.eu) or in Discord (www.grv.sh/discord)."
  successfulcctivated: "&c[&42FA&c]&7 You have successfully confirmed your account. 2FA is now enabled for you."
  needtoactivate: "&c[&42FA&c]&7 It seems that you have already activated 2FA but not yet confirmed it. &c&lTherefor it's not protecting your account yet! &7Confirm 2FA by running /2fa activate <6 digit code from the app>."
  loginsuccessful: "&c[&42FA&c]&a Confirmation successful!"
  waitingforauthcode: "&c[&42FA&c]&7 Please enter your 6 digit code in the chat first before performing this action."
  forceenable: '&c[&42FA&c]&c You need to enable 2FA before you can play. Use &e/2fa enable&c to enable 2FA.'
  disableforforced: '&c[&42FA&c]&c You are not allowed to disable 2FA for your account!'
  datanull: '&c[&42FA&c]&c Data can not be loaded! Please rejoin once and if that doesn''t help report this issue on our Discord (www.grv.sh/discord).'
  yubikey:
    activated: '&c[&42FA&c]&a YubiKey has been added!'
    invalidcode: '&c[&42FA&c]&c The YubiKey OTP is invalid!'
    enabletotp: '&c[&42FA&c]&c You must have TOTP enabled before you can add a YubiKey!'
    addyubiusage: '&c[&42FA&c]&7 To add a YubiKey please use the command like this: &l/2fa yubikey add <name> <OTP>'
    removeyubiusage: '&c[&42FA&c]&7 To remove a YubiKey please use the command like this: &l/2fa yubikey remove <name>'
    subcommands: '&c[&42FA&c]&7 You can perform the following actions: &f&lremove <name>&r&7, &f&ladd <name> <OTP> &r&7or &f&llist'
    disabled: '&c[&42FA&c]&c YubiKey support is disabled by an administrator.'
    removedkey: '&c[&42FA&c]&a The YubiKey has been removed from your account.'
    removedkeynotfound: '&c[&42FA&c]&c Your account does not have a YubiKey with the specified name.'
    keysinaccount: '&c[&42FA&c]&7 You have added the following YubiKeys to your account:'
    nokeysinaccount: '&c[&42FA&c]&c You have not added any YubiKeys to your account.'
    keylist: '&7&l- &a&l%name% &8(%publicId%)'
  hovertext: '&cOpen link'
